### ISSUE TITLE
Not responsive for all screen sizes

### ISSUE THREAD

**Issue by gauravdas014** [sjsakib/cfviz#25] opened 2020-07-02 13:26 UTC
![Screenshot (222)](https://user-images.githubusercontent.com/51530678/86364677-1ca65300-bc96-11ea-9e11-75bcfe7f1ea3.png)
It will be nice if the website is made responsive to different screen sizes, I would like to contribute to this if permitted.

**Comment by sjsakib** [comment] 2020-07-03 13:01
Thank you for reporting.

What screen size causes problem? And how do you plan to fix it?

**Comment by gauravdas014** [comment] 2020-07-04 03:05
The problem starts appearing at screen size: 1020 px. After this screen size, the submission heatmap graph gets cropped. At 900 px the chart of verdicts and languages starts getting cropped. I thought to fix the bug using flex. On smaller screen sizes I thought to use the flex-direction column so that the charts align vertically. But it's not working this way. Suggest me if you have any idea how to fix it. I will try to figure it out on my local device and if I can do it, I will let you know.

**Comment by sjsakib** [comment] 2020-07-06 07:45
The screenshots you included, they are intended behavior. The charts are horizontally scroll-able. I think they work pretty well. And besides you probably resized the screen after the charts were drawn. If the screen is smaller when the graphs are being drawn, smaller graphs will be drawn.

**Comment by sjsakib** [comment] 2020-07-06 07:46
I am closing the issue for now, let me know if you still have something

**Closed as completed by sjsakib** 2020-07-06 07:46 UTC
