### ISSUE TITLE
Cannot read property 'Do' of undefined

### ISSUE THREAD

**Issue by EndlessCheng** [sjsakib/cfviz#31] opened 2021-07-14 02:41 UTC
https://cfviz.netlify.app/compare.html

![image](https://user-images.githubusercontent.com/7086966/125552324-31c5e02a-0bb7-4a5a-b9cb-f4f3bf37d7de.png)

**Comment by Dip707** [comment] 2021-07-19 00:02
@sjsakib please check this, might be a small bug, will help the cp community very much if fixed

**Comment by sjsakib** [comment] 2021-07-20 06:19
Duplicate of #30

**Closed as completed** 2021-07-20 06:20 UTC
