### ISSUE TITLE
Considers base rating as 1200 for first contest

### ISSUE THREAD

**Issue by ankushkhanna1998** [sjsakib/cfviz#20] opened 2020-05-24 02:02 UTC
I recently did a profile test and found out that now it is considering the base rating (that is, the rating before any contest) as 1200 instead of 1500 (which is the base rating for a user that Codeforces considers).

Due to this, the ```Max up``` is showing up as ```288``` (actually I had a ```-12``` for my first contest, as my first rating was ```1488```), and that surely isn't my ```Max up``` as of now. I clearly remember that earlier it used to work correctly.

**Comment by sjsakib** [comment] 2020-06-02 17:02
duplicate of #21

**Comment by sjsakib** [comment] 2020-06-02 17:03
Duplicate of #21

**Closed as completed** 2020-06-19 17:00 UTC
